name: Deploy

on:
  push:
    branches:
      - 'release'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
     - name: Deploy
       if: github.event_name != 'pull_request'
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_USER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script_stop: true
          script: |
            cd /data/www/hexo_blog_public/ && git pull
            curl ${{ secrets.BARK_KEY }}/hexo/blog发布完成